// src/lib/faq-generator.ts
// Parses FAQ blocks from generated articles and structures them for schema injection

export interface FAQ {
  question: string
  answer: string
}

export interface FAQParseResult {
  faqs: FAQ[]
  rawBlock: string        // the original FAQ section text
  articleWithoutFAQ: string  // article body with FAQ section removed (for clean display)
}

// Parses the FAQ section from the article body.
// Handles two formats:
//   1. HTML: <div class="faq-item"><h3>Q?</h3><p>Answer</p></div>
//   2. Markdown: **Q: question**\nA: answer
// Also tries extracting from the inline FAQPage JSON-LD script.
export function parseFAQsFromArticle(articleContent: string): FAQParseResult {
  // --- FORMAT 1: HTML faq-item divs (primary format generated by Claude) ---
  const htmlFaqPattern = /<div[^>]*class=["'][^"']*faq-item[^"']*["'][^>]*>([\s\S]*?)<\/div>/gi
  const htmlFaqs: FAQ[] = []
  let htmlMatch: RegExpExecArray | null
  // We need to reset lastIndex since we're reusing the regex
  htmlFaqPattern.lastIndex = 0
  while ((htmlMatch = htmlFaqPattern.exec(articleContent)) !== null) {
    const inner = htmlMatch[1]
    const qMatch = inner.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)
    const aMatch = inner.match(/<p[^>]*>([\s\S]*?)<\/p>/i)
    if (qMatch && aMatch) {
      const question = qMatch[1].replace(/<[^>]+>/g, '').trim()
      const answer = aMatch[1].replace(/<[^>]+>/g, '').trim().replace(/\s+/g, ' ')
      if (question && answer && question.length > 5) {
        htmlFaqs.push({ question: question.endsWith('?') ? question : question + '?', answer })
      }
    }
  }
  if (htmlFaqs.length >= 2) {
    return { faqs: htmlFaqs.slice(0, 8), rawBlock: '', articleWithoutFAQ: articleContent }
  }

  // --- FORMAT 1b: FAQ H2 section with bare <h3>Q</h3><p>A</p> (no faq-item class) ---
  const faqHeadingSplit = articleContent.split(/<h2[^>]*>\s*(?:Frequently Asked Questions|FAQ|FAQs)\s*<\/h2>/i)
  if (faqHeadingSplit.length >= 2) {
    const afterFaq = faqHeadingSplit[1]
    const untilNextH2 = afterFaq.split(/<h2[\s>]/i)[0] || afterFaq
    const h3Faqs: FAQ[] = []
    const h3Pattern = /<h3[^>]*>([\s\S]*?)<\/h3>\s*<p[^>]*>([\s\S]*?)<\/p>/gi
    let h3Match: RegExpExecArray | null
    while ((h3Match = h3Pattern.exec(untilNextH2)) !== null) {
      const question = h3Match[1].replace(/<[^>]+>/g, '').trim()
      const answer = h3Match[2].replace(/<[^>]+>/g, '').trim().replace(/\s+/g, ' ')
      if (question.length > 5 && answer.length > 10) {
        h3Faqs.push({ question: question.endsWith('?') ? question : question + '?', answer })
      }
    }
    if (h3Faqs.length >= 2) {
      return { faqs: h3Faqs.slice(0, 8), rawBlock: '', articleWithoutFAQ: articleContent }
    }
  }

  // --- FORMAT 2: Try extracting from FAQPage JSON-LD in the article ---
  const jsonLdPattern = /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi
  let ldMatch: RegExpExecArray | null
  jsonLdPattern.lastIndex = 0
  while ((ldMatch = jsonLdPattern.exec(articleContent)) !== null) {
    try {
      const parsed = JSON.parse(ldMatch[1])
      if (parsed['@type'] === 'FAQPage' && Array.isArray(parsed.mainEntity)) {
        const faqs: FAQ[] = parsed.mainEntity
          .filter((e: { '@type': string; name?: string; acceptedAnswer?: { text?: string } }) => e['@type'] === 'Question' && e.name && e.acceptedAnswer?.text)
          .map((e: { name: string; acceptedAnswer: { text: string } }) => ({
            question: e.name.trim(),
            answer: e.acceptedAnswer.text.trim(),
          }))
        if (faqs.length >= 2) {
          return { faqs: faqs.slice(0, 8), rawBlock: '', articleWithoutFAQ: articleContent }
        }
      }
    } catch { /* continue */ }
  }

  // --- FORMAT 3: Markdown **Q: ...** / A: format ---
  const faqSectionRegex = /##\s*Frequently Asked Questions\s*\n([\s\S]*?)(?=\n##|\n#(?!#)|$)/i
  const faqMatch = articleContent.match(faqSectionRegex)

  if (!faqMatch) {
    return { faqs: [], rawBlock: '', articleWithoutFAQ: articleContent }
  }

  const rawBlock = faqMatch[0]
  const faqContent = faqMatch[1]

  const qaPattern = /\*\*Q:\s*(.+?)\*\*\s*\nA:\s*([\s\S]+?)(?=\n\*\*Q:|\n\n\*\*Q:|$)/gi
  const faqs: FAQ[] = []
  let match: RegExpExecArray | null

  while ((match = qaPattern.exec(faqContent)) !== null) {
    const question = match[1].trim().replace(/\?$/, '').trim() + '?'
    const answer = match[2].trim().replace(/\n+/g, ' ')
    if (question && answer) {
      faqs.push({ question, answer })
    }
  }

  // Fallback: simple pair splitting
  if (faqs.length === 0) {
    const simplePairs = faqContent.split(/\n\n+/)
    for (const pair of simplePairs) {
      const lines = pair.trim().split('\n')
      if (lines.length >= 2) {
        const q = lines[0].replace(/^\*\*Q?:?\s*\*?\*?/, '').replace(/\*\*$/, '').trim()
        const a = lines.slice(1).join(' ').replace(/^A?:?\s*/, '').trim()
        if (q.length > 10 && a.length > 20) {
          faqs.push({ question: q.endsWith('?') ? q : q + '?', answer: a })
        }
      }
    }
  }

  const articleWithoutFAQ = articleContent.replace(rawBlock, '').trim()

  return { faqs: faqs.slice(0, 8), rawBlock, articleWithoutFAQ }
}

// Validates FAQ quality — returns issues if FAQs are too generic
export function validateFAQQuality(faqs: FAQ[]): string[] {
  const issues: string[] = []
  const genericQuestions = ['what is', 'why is', 'when did', 'who is']

  if (faqs.length < 4) {
    issues.push(`Only ${faqs.length} FAQs generated — aim for 6`)
  }

  const tooShort = faqs.filter(f => f.answer.split(' ').length < 20)
  if (tooShort.length > 0) {
    issues.push(`${tooShort.length} FAQ answers are too short (under 20 words)`)
  }

  const genericCount = faqs.filter(f =>
    genericQuestions.some(g => f.question.toLowerCase().startsWith(g))
  ).length

  if (genericCount > faqs.length / 2) {
    issues.push('Too many generic questions — add more specific, actionable questions')
  }

  return issues
}
