import { describe, expect, it, vi } from 'vitest'
import { detectTrailingSlashDuplicates } from '@/lib/fix-strategies/topic-8'
import { normalizeFixStrategyUrl } from '@/lib/fix-strategies/shared'

const ORIGIN = 'https://example.com'

function html(body: string): string {
  return `<!doctype html><html><head><title>t</title></head><body>${body}</body></html>`
}

describe('topic 8 discoverability gate', () => {
  it('GENERATED-ONLY peer → informational, not actionable finding', async () => {
    const body = html('<p>same</p>')
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const path = new URL(String(input)).pathname
      if (path === '/page' || path === '/page/') {
        return new Response(body, {
          status: 200,
          headers: { 'content-type': 'text/html' },
        })
      }
      return new Response('no', { status: 404 })
    })
    const deps = { fetch: fetchMock as unknown as typeof fetch }
    const discovered = new Set(
      [`${ORIGIN}/page`].map((u) => normalizeFixStrategyUrl(u)!),
    )
    // /page/ is NOT in the discovery set — only generated by the probe
    const result = await detectTrailingSlashDuplicates(
      [{ url: `${ORIGIN}/page`, body }],
      { deps, discoveredNormalized: discovered },
    )
    expect(result.findings).toHaveLength(0)
    expect(result.informational[0]?.verdict).toBe(
      'informational-generated-only',
    )
    expect(result.informational[0]?.discoverability).toBe('generated-only')
  })

  it('DISCOVERED peer → surface finding (human-review for site-wide config)', async () => {
    const body = html('<p>same</p>')
    const fetchMock = vi.fn(async (input: RequestInfo | URL) => {
      const path = new URL(String(input)).pathname
      if (path === '/page' || path === '/page/') {
        return new Response(body, {
          status: 200,
          headers: { 'content-type': 'text/html' },
        })
      }
      return new Response('no', { status: 404 })
    })
    const deps = { fetch: fetchMock as unknown as typeof fetch }
    const discovered = new Set(
      [`${ORIGIN}/page`, `${ORIGIN}/page/`].map(
        (u) => normalizeFixStrategyUrl(u)!,
      ),
    )
    const result = await detectTrailingSlashDuplicates(
      [{ url: `${ORIGIN}/page`, body }],
      {
        deps,
        discoveredNormalized: discovered,
        signals: {
          sitemapUrls: [`${ORIGIN}/page`],
          trailingSlashConfig: false,
        },
      },
    )
    expect(result.informational).toHaveLength(0)
    expect(result.findings[0]?.verdict).toBe('human-review-blast-radius')
    expect(result.findings[0]?.declarationSite).toBe('config:next.config.js')
    expect(result.findings[0]?.discoverability).toBe('discovered')
  })
})
